security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main_resetting:
            pattern: ^/resetting/
            anonymous: true
        main_register:
            pattern:   ^/register/
            anonymous: true
        main_login:
            pattern:   ^/login$
            anonymous: true
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: /
                success_handler: redirect.after.login
            logout:       true
            anonymous:    false
         

    access_control:
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }