# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    gestionssh:
        class: MainBundle\Services\GestionSSH
        arguments: ["%ssh_host%","%ssh_login%","%ssh_password%"]
