FROM debian

MAINTAINER Jerome<jerome.martinsmosca@etud.univ-angers.fr>

# Application
RUN apt-get update && apt-get install -y wget && apt-get install -y ssh && apt-get install -y g++

WORKDIR /home
