main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

language_info:
    path:   /language_info
    defaults: { _controller: MainBundle:Default:languageInfo }

vue_console:
    path:    /console
    defaults: { _controller: MainBundle:Console:index }
    
exec:
    path:    /exec
    defaults: {_controller: MainBundle:Console:exec }
    
answer:
    path:    /answer
    defaults: {_controller : MainBundle:Console:answer }
    
register:
    path:    /register
    defaults: {_controller : MainBundle:Registration:register }
    
register_check:
    path:    /registerCheck
    defaults: {_controller : MainBundle:Registration:check }