main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

language_info:
    path:   /language_info
    defaults: { _controller: MainBundle:Default:languageInfo }
    
save_code:
    path:    /save_code
    defaults: {_controller : MainBundle:Default:saveCode }

update_interface:
    path:    /update_interface
    defaults: {_controller : MainBundle:Default:updateInterface }

vue_console:
    path:    /console
    defaults: { _controller: MainBundle:Console:index }
    
exec:
    path:    /exec
    defaults: {_controller: MainBundle:Console:exec }
    
answer:
    path:    /answer
    defaults: {_controller : MainBundle:Console:answer }

stop_docker:
    path: /stop_exec
    defaults: {_controller : MainBundle:Console:stop }