main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

language_info:
    path:   /language_info
    defaults: { _controller: MainBundle:Default:languageInfo }

vue_console:
    path:    /console
    defaults: { _controller: MainBundle:Console:index }
    
output:
    path:    /get_output
    defaults: {_controller: MainBundle:Console:output }
    
input:
    path:    /get_input
    defaults: {_controller : MainBundle:Console:input }