main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

language_info:
    path:   /language_info
    defaults: { _controller: MainBundle:Default:languageInfo }

vue_console:
    path:    /console
    defaults: { _controller: MainBundle:Console:index }

executer_commande:
    path:    /executer_commande
    defaults: { _controller: MainBundle:Console:traiter }
