main_homepage:
    path:     /console
    defaults: { _controller: MainBundle:Console:index }

executer_commande:
    path:    /executer_commande
    defaults: { _controller: MainBundle:Console:traiter }
