services:
    gestionssh:
        class: MainBundle\Services\GestionSSH
        arguments: ["%ssh_host%","%ssh_login%","%ssh_password%"]

    maindbundle.contains_mail_validator:
        class: MainBundle\Validator\Constraints\ContainsMailValidator
        arguments: ["%mails_suffixe%"]
        tags:
            - { name: validator.constraint_validator }

       
