services:
    ssh_connection_handler:
        class: MainBundle\Services\SshConnectionHandler
        arguments: ["%ssh_host%", "%ssh_port%", "%ssh_login%", "%ssh_password%", "@logger"]
 #       tags:
#            - {name: monolog.logger, channel: app }
    docker_manager:
        class: MainBundle\Services\DockerManager
        arguments: ["@logger", "@ssh_connection_handler", "%docker_stop_timeout%", "%add_hosts%", "%docker_cpu%", "%docker_memory%"]
    maindbundle.contains_mail_validator:
        class: MainBundle\Validator\Constraints\ContainsMailValidator
        arguments: ["%mails_suffixe%"]
        tags:
            - { name: validator.constraint_validator }
    docker.subscriber:
        class: MainBundle\EventListener\DockerSubscriber
        arguments : ["@ssh_connection_handler"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

       
